spring:
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-id: eaf543a2004f4557a06ceeafa5858684
            client-secret: secret
            provider: spotify-provider
            client-authentication-method: basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user-read-private,user-read-email
        provider:
          spotify-provider:
            authorization-uri: https://accounts.spotify.com/authorize?show_dialog=true
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: id